#!/usr/bin/env node
// Bake the public Layer 0 corpus into src/corpus.generated.ts so the Worker
// bundles it (zero runtime egress). Reads from a sibling portfolio-index checkout
// by default, or from the live site with --url.
//
//   node scripts/build-corpus.mjs                       # ../portfolio-index
//   PORTFOLIO_DIR=/path node scripts/build-corpus.mjs   # explicit local dir
//   node scripts/build-corpus.mjs --url=https://saagarpatel.dev
//
// The corpus is already public (served as HTML + JSON), so nothing private is
// introduced by baking it.

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const args = process.argv.slice(2);
const urlArg = args.find((a) => a.startsWith("--url="))?.slice("--url=".length);
const dirArg =
	args.find((a) => a.startsWith("--dir="))?.slice("--dir=".length) ??
	process.env.PORTFOLIO_DIR ??
	"../portfolio-index";

async function fromUrl(base) {
	const get = async (path) => {
		const res = await fetch(`${base}/${path}`);
		if (!res.ok) throw new Error(`GET ${path} -> ${res.status}`);
		return res.json();
	};
	const index = await get("corpus-index.json");
	const documents = {};
	for (const d of index.documents) documents[d.id] = await get(`corpus/${d.id}.json`);
	const projects = await get("projects-data.json");
	return { index, documents, projects };
}

function fromDir(dir) {
	const root = resolve(dir);
	const read = (rel) => JSON.parse(readFileSync(join(root, rel), "utf8"));
	const index = read("corpus-index.json");
	const documents = {};
	for (const d of index.documents) documents[d.id] = read(`corpus/${d.id}.json`);
	const projects = read("projects-data.json");
	return { index, documents, projects };
}

const corpus = urlArg ? await fromUrl(urlArg) : fromDir(dirArg);

const out =
	"// AUTO-GENERATED by scripts/build-corpus.mjs — do not edit by hand.\n" +
	'import type { Corpus } from "./types";\n\n' +
	`const corpus: Corpus = ${JSON.stringify(corpus)};\n\n` +
	"export default corpus;\n";

writeFileSync(new URL("../src/corpus.generated.ts", import.meta.url), out);
console.log(
	`baked corpus: ${corpus.index.documents.length} docs, ` +
		`${Object.keys(corpus.projects.curated).length} curated projects ` +
		`(source: ${urlArg ?? resolve(dirArg)})`,
);
