// Shape of the baked Layer 0 corpus (generated by the portfolio-index build:
// corpus-index.json + corpus/<id>.json + projects-data.json). The MCP server is a
// pure read layer over these public, already-served artifacts.

export type DocType = "essay" | "chapter" | "note" | "page";

/** One row of corpus-index.json: light metadata, no body. */
export interface IndexRecord {
	id: string; // path without .html, e.g. "writing/the-handoff"
	slug: string; // last path segment, e.g. "the-handoff"
	type: DocType;
	title: string;
	description: string;
	url: string; // canonical https URL
	date: string | null; // YYYY-MM-DD git commit date, or null if uncommitted
	word_count: number;
}

/** One corpus/<id>.json: the index record plus the full Markdown body. */
export interface FullDoc extends IndexRecord {
	body_markdown: string;
}

export interface CorpusIndex {
	site: string;
	title: string;
	summary: string;
	generated: string | null;
	counts: Record<string, number>;
	documents: IndexRecord[];
}

/** A curated (named, public-safe) project from projects-data.json. */
export interface ProjectRecord {
	slug: string;
	stack: string[];
	status: string | null; // null when the auditor has no activity signal
	lifecycle: string | null; // null when the repo declares no lifecycle state
	last_active: string | null; // YYYY-MM-DD, or null when uncommitted/undated
	tests: boolean;
	ci: boolean;
}

export interface ProjectsArchive {
	total: number;
	maintained: number;
	tested: number;
	ci: number;
	shown: number;
	stacks: unknown[];
	lifecycle: unknown[];
}

export interface ProjectsData {
	generated_at: string;
	source_schema_version: string;
	public: boolean;
	curated: Record<string, Omit<ProjectRecord, "slug">>;
	archive: ProjectsArchive;
}

export interface RepoProfileIndexRecord {
	repo_id: string;
	display_name: string;
	public_reference: string;
	attention_state: string;
	context_quality: string;
	freshness_status: string;
	profile_json: string;
	receipt_count: number;
	pending_proof_count?: number;
}

export interface RepoProfileIndex {
	schema_version: string;
	generated_at: string;
	source: string;
	source_schema_version?: string;
	profile_count: number;
	profiles: RepoProfileIndexRecord[];
	public_safety: {
		policy: string;
		excluded_categories: string[];
	};
	integrity?: Record<string, unknown>;
}

export interface RepoProfile {
	schema_version: string;
	repo_id: string;
	display_name: string;
	public_reference: string;
	visibility: Record<string, unknown>;
	summary: {
		purpose: string;
		category: string;
		attention_state: string;
		context_quality: string;
		stack?: string[];
		has_tests?: boolean;
		has_ci?: boolean;
		last_meaningful_activity?: string | null;
		risk_tier?: string;
	};
	owner_boundary: Record<string, unknown>;
	runbook: Record<string, unknown>;
	agent_surfaces: Record<string, unknown>;
	proof_refs: Array<Record<string, unknown>>;
	freshness: Record<string, unknown>;
	excluded_data: Array<Record<string, unknown>>;
	limitations: string[];
	integrity: Record<string, unknown>;
}

export interface RepoProfilesData {
	index: RepoProfileIndex;
	profiles: Record<string, RepoProfile>;
}

/** One model's calibration profile from the public OPERANT mirror. */
export interface OperantModel {
	display_name: string;
	ocs_mean: number | null;
	ocs_stdev: number | null;
	orchestration_mean: number | null;
	run_family: string;
	subject_shell: string;
}

/** Public, sanitized OPERANT results (calibration profiles + presentation figures),
 * sourced from the published mirror github.com/saagpatel/operant. */
export interface OperantData {
	profiles: {
		generated_at?: string;
		included_lab_labels?: string[];
		models: OperantModel[];
		presentation?: unknown;
		source_result_policy?: string;
	};
	figures: Record<string, unknown>;
}

/** The single baked artifact the Worker bundles. */
export interface Corpus {
	index: CorpusIndex;
	documents: Record<string, FullDoc>; // keyed by id
	projects: ProjectsData;
	repoProfiles?: RepoProfilesData | null; // optional until the profile artifacts are published
	operant?: OperantData | null; // optional: only present when baked from local sources
}
